### ISSUE TITLE
Interpreting results after training algorithms

### ISSUE THREAD

**Issue by divyat09** [facebookresearch/DomainBed#3]
I  tried to train the algorithm ERM on PACS dataset. The final logs at the end of training are as follows:

env0_in_acc   env0_out_acc  env1_in_acc   env1_out_acc  env2_in_acc   env2_out_acc  env3_in_acc   env3_out_acc  epoch         loss          step          step_time

0.8377059182  0.8239608802  0.9845415778  0.9423076923  0.9947604790  0.9670658683  0.9812340967  0.9299363057  3900.0000000  0.0155880866  3900          0.5439552005

However, I do not understand what do they represent. If out_acc represents the out of domain accuracy then the numbers do not make sense, since its greater than 90 percent for 3 domains, while in PACS only the test domain Photo obtains more than 90 percent out of domain accuracy

How do I obtain the out of domain accuracy on individual test domains ( Photo, Art Painting, Cartoon, Sketch )?

**Comment by lopezpaz** [comment]
`envX_in_acc` and `envX_out_acc` are classification accuracies for the `in` and `out` splits for environment `X`, respectively. The `out` split is often smaller, containing `args.holdout_fraction` of the examples for that environment. When environment `X` is a training domain, the `in` split is used for training, and the `out` split is used for model selection. When environment `X` belongs to the testing domains, the `in` split is used for computing the final test accuracy, and the `out` split is used for model selection (only oracle).

Since we sort domains alphabetically, in your example the numbers represent:
```
env0_in_acc (domain A, in split)
env0_out_acc (domain A, out split)
env1_in_acc (domain C, in split)
env1_out_acc (domain C, out split)
env2_in_acc (domain P, in split)
env2_out_acc (domain P, out split)
env3_in_acc (domain S, in split)
env3_out_acc (domain S, out split)
```
Without knowing your `args.test_envs` I cannot say which one is your *test domain*, but it should be easy to find out for you.
