### ISSUE TITLE
Implement checkpointing

### ISSUE THREAD

**Issue by SirRob1997** [facebookresearch/DomainBed#33]
The way it is currently implemented, we save the model parameters [after the last training step](https://github.com/facebookresearch/DomainBed/blob/master/domainbed/scripts/train.py#L196) is finished. However, this doesn't conveniently allow users to access the best performing model parameters for different validation techniques. In fact, I think only the parameters for oracle validation can be accessed this way, as early stopping is disabled there and with the [printing of the best-performing hyperparameters](https://github.com/facebookresearch/DomainBed/blob/master/domainbed/scripts/list_top_hparams.py), we can obtain the respective tuning step. 

To support the other validation techniques, it would probably be helpful to have a flag where we persist model parameters at each validation checkpoint. Once we run [`collect_results.py`](https://github.com/facebookresearch/DomainBed/blob/master/domainbed/scripts/collect_results.py), we might also have an option to prune these model checkpoints and only keep the ones that correspond to the best-performing one for a specific validation technique and test environment. This would help to save disk space (we keep only <img src="https://render.githubusercontent.com/render/math?math=\mathrm{num_domains} \times \mathrm{num_validation_techniques}"> model checkpoints) and make it even more convenient to browse through them.

Maybe there is even an option of implementing this that would be better.

**Comment by igul222** [comment]
I've added a flag to train.py; see https://github.com/facebookresearch/DomainBed/commit/32cbebbb719aec259b4470522d9c8efea27b1624 . I'm hesitant to add support for this to sweep.py because the changes are complicated and even a single sweep would end up generating quite a lot of weight files (also, it's best if we can keep collect_results.py idempotent). As an alternative, I suggest running a sweep and re-running specific hparam combinations whose weights you want to inspect in more detail. Closing for now; feel free to reopen if you see any problems.
