### ISSUE TITLE
about domain adaptation

### ISSUE THREAD

**Issue by Neronjust2017** [facebookresearch/DomainBed#46]
Hi, when I run "python train.py --data_dir=../../dataset/ --algorithm ERM --dataset RotatedMNIST --task domain_adaptation --uda_holdout_fraction 0", I got the error below. I did't modify the code, is there someting wrong? What' the meaning of "uda_holdout_fraction"?  Thanks!
`Traceback (most recent call last):
File "/home/weiyuhua/Code/DomainBed/domainbed/scripts/train.py", line 211, in <module>
for x,_ in next(uda_minibatches_iterator)]
StopIteration`

**Comment by lopezpaz** [comment]
Fixed in master. The argument `--uda_holdout_fraction` is the percentage of examples from the test domain that DomainBed will provide (unlabeled) to the algorithm during training, provided that `--task=domain_adaptation`. Note that the current implementation of algorithms do not use the unlabeled data at all, you would have to include that functionality.
